### ISSUE TITLE
cython should be a dependency of vtzero

### ISSUE THREAD

**Issue by Plantain** [mapbox/vtzero#48]
(env) laptop% pip install vtzero
Collecting vtzero
  Using cached https://files.pythonhosted.org/packages/4a/70/d5171240be0bfe4d6ae0002a19c9ee0bd17d1a7670facfad471a023c58ad/vtzero-0.0.1b1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1wgby62w/vtzero/setup.py", line 5, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1wgby62w/vtzero/
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

I believe this is possible with PEP518

**Comment by Plantain** [comment]
Wrong vtzero package.
